org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=toolpouch
mod.name=Tool Pouch
mod.group=me.pajic
mod.version=1.0.13
mod.channel_tag=
mod.authors=pajic
mod.contributors=Moonkey
mod.license=MIT
mod.description=Store tools, equipment and storage items in the Tool Pouch to make them more useful
mod.sources_url=https://github.com/pajicadvance/toolpouch
mod.homepage_url=https://modrinth.com/mod/tool-pouch
mod.issues_url=https://github.com/pajicadvance/toolpouch/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fzzy_config=[VERSIONED]
deps.ldl=[VERSIONED]
deps.sbt=[VERSIONED]
deps.raised=[VERSIONED]
deps.locastones=[VERSIONED]
deps.trinkets=[VERSIONED]
deps.ohmega=[VERSIONED]

publish.modrinth=ZY6C1rJ4
publish.curseforge=1459801
publish.github=false
