modLoader = "javafml"
loaderVersion = "[2,)"
license = "${license}"
issueTrackerURL = "${issues_url}"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
displayURL = "${homepage_url}"
modUrl = "${homepage_url}"
logoFile = "icon.png"
authors = "${authors}"
logoBlur = false
credits = "${contributors}"

description = '''${description}'''

[modproperties.${id}."yumi:entrypoints"]
"lambdynlights:initializer" = "${group}.${id}.renderer.PlayerLanternDynamicLighting"
[[mixins]]
config = "${id}.mixins.json"
behaviorVersion = "0.17.0"
[[accessTransformers]]
file = "aw/${minecraft}.cfg"
${dependencies}
