deps.minecraft=26.1.2
deps.fabric-api=0.146.1+26.1.2
deps.modmenu=18.0.0-alpha.8
deps.fzzy_config=0.7.6+26.1-pre-3
deps.ldl=4.10.0-rc.1+26.1
deps.raised=Fabric-26.1.1-5.1.2
deps.sbt=5.2.18+26.1
deps.locastones=1.5.2+26.1+A
deps.trinkets=4.0.0-alpha.3+26.1
deps.ohmega=1.5.18-mc26.1.2
deps.spyglassastronomy=1.0.20-mc26.1.1

publish.additionalVersions=26.1, 26.1.1
